/**:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.173
    max_hamming: 0
    qos_profile: default

    detector:
      threads: 1
      decimate: 2.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    pose_estimation_method: "pnp"

    tag:
      ids: [1, 9, 10]
      frames: [tag_1, tag_9, tag_10]
      sizes: [0.01, 0.05, 0.10]
